### ISSUE TITLE
RPI Access without root permission? 

### ISSUE THREAD

**Issue by naty6458** [nRF24/pyRF24#15]
Hi Hello ,
I tried to run the "RF24Mesh_Example_Master.py" through a non-ROOT user, and without SUDO. I gave the user permissions to GPIO and SPI. And from there I get a message.  

`Traceback (most recent call last):
  File "/home/naty/rf24libs/RF24Mesh/examples_RPi/RF24Mesh_Example_Master.py", line 20, in <module>
    radio.begin()
RuntimeError: Process should run as root`

I would love to know what can be done to activate the RADIO without ROOT permission.
Thanks!

**Comment by 2bndy5** [comment]
How did you install the lib? The example you executed was designed for the individual python wrapper for RF24Mesh. This repo is for the pyRF24 package which wraps the RF24, RF24Network, and RF24Mesh libs into 1 python package.

<details><summary>The main difference between pyRF24 vs individual wrappers</summary>

The pyRF24 pkg is installable via `pip install pyrf24`. The individual wrappers need to be built/installed separately.
> **Note**
> The pyRF24 doesn't link to any installed RF24* C++ lib as it ships with its own built binary drivers (`librf24*.so` files).

</details> 

## Please disclose more detail

It sounds like you're using an Ubuntu OS since you modified the permissions of the user manually; the RPi OS does this for you (or at least it did). If you're indeed using the RPi OS (formerly known as Raspbian), then I'm guessing you built/installed the C++ libs using RPi or pigpio drivers. The SPIDEV (highly recommended) and MRAA drivers don't typically require root permissions.

Lastly, running `sudo` on a python script can have a negative impact if using a python virtual environment (venv for short). I don't think this is your problem because the error message would've been completely different (something like "could not find module X").

> I tried to run the previous one

What "previous one"? It seems like you made an edit here before posting.

**Comment by naty6458** [comment]
Thank you very much for the response, 

Sorry for the bad English. I fixed the main post

i install with `pip install pyrf24`.

`Raspberry Pi 3 Model B Plus Rev 1.3
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"`

Do I need to install pigpio, SPIDEV and the MRAA website?

I am trying to run the script without a virtual environment, but through the terminal through my USER.

The script works fine if I run via SUDO.

Thanks! 
 
 
<img width="462" alt="image" src="https://github.com/nRF24/pyRF24/assets/44592421/f5a89172-ab92-47ff-abc8-29cba6fd7a01">

**Comment by 2bndy5** [comment]
Ok, now that you have pyrf24 installed, you can simply run [one of the examples included in this repository](https://github.com/nRF24/pyRF24/tree/main/examples):

```
git clone https://github.com/nRF24/pyRF24
cd pyRF24/examples
python mesh_example.py
# or
python mesh_example_master.py
```

By default this pyRF24 package shouldn't need root permission, but it won't work with the older examples (located in RF24, RF24Network, and RF24Mesh repositories). Please also read [migrating to pyrf24 section](https://pyrf24.readthedocs.io/en/latest/#migrating-to-pyrf24).

Your problem is that you installed RF24 C++ lib using RPi driver which absolutely requires root permission (and should not be bypassed). It would be better to install the RF24 C++ library using the SPIDEV driver as it does not need root permission. The pyRF24 package ships with binaries built using the SPIDEV driver.

**Comment by naty6458** [comment]
<img width="373" alt="image" src="https://github.com/nRF24/pyRF24/assets/44592421/599602bd-5b3f-48a5-b7c6-7fabbf9036f4">

Thank you very much for the response,

same problem....

**Comment by 2bndy5** [comment]
That is a wiring or pin numbering problem. The examples' original code uses GPIO22 for CE pin and GPIO8 for CSN pin.
```python
########### USER CONFIGURATION ###########
# See https://github.com/TMRh20/RF24/blob/master/pyRF24/readme.md
# Radio CE Pin, CSN Pin, SPI Speed
# CE Pin uses GPIO number with BCM and SPIDEV drivers, other platforms use
# their own pin numbering
# CS Pin addresses the SPI bus number at /dev/spidev<a>.<b>
# ie: RF24 radio(<ce_pin>, <a>*10+<b>); spidev1.0 is 10, spidev1.1 is 11 etc..
radio = RF24(22, 0)
```

**Comment by naty6458** [comment]
Thank you very much, I will do a double check, on the whole issue of GPIO permissions

**Comment by 2bndy5** [comment]
The RPi driver uses the BCM2835 library. The [BMC2835 library](https://www.airspayce.com/mikem/bcm2835/) uses direct Input/Output access to the Raspberry Pi's CPU. It is not recommended to bypass the needed root permission since it would allow the user to potentially turn the Raspberry Pi into a useless brick.

If using the SPIDEV driver on Ubuntu, users will need to alter the user permission to access GPIO and SPI devices, but the SPIDEV driver cannot turn your Raspberry Pi into a brick (regardless of user permissions).

**Comment by 2bndy5** [comment]
Also, the SPIDEV driver is significantly faster than the RPi driver.

**Comment by naty6458** [comment]
Thank you very much for the extensive information, you have updated me a lot, in the past I really used the UBUNTU base

<img width="313" alt="image" src="https://github.com/nRF24/pyRF24/assets/44592421/057cba05-83b2-4a82-902b-0012b3eee829">

I change the gpio from gpio 17 to gpio 22 , to the defult and its work!  

Thanks!!!!  :-)
